from __future__ import annotations

import json
import os
import re
from pathlib import Path

from .audit import default_state_dir, log_event
from .models import ToolSpec
from .platform_support import detect_platform


def load_config(path: Path | None = None) -> dict:
    path = path or default_state_dir() / "config.json"
    if not path.exists():
        return {"tool_paths": {}, "variables": {}}
    return json.loads(path.read_text(encoding="utf-8"))


def save_config(config: dict, path: Path | None = None) -> Path:
    path = path or default_state_dir() / "config.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(config, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return path


def configure_environment(specs: list[ToolSpec], config: dict | None = None) -> dict:
    import shutil

    config = config or {"tool_paths": {}, "variables": {}}
    paths = dict(config.get("tool_paths", {}))
    variables = dict(config.get("variables", {}))
    for spec in specs:
        executable = shutil.which(spec.executable)
        if not executable:
            continue
        paths[spec.name] = str(Path(executable).parent)
        for key, value in spec.environment.items():
            variables[key] = value.replace("{path}", executable)
    return {"tool_paths": dict(sorted(paths.items())), "variables": dict(sorted(variables.items()))}


def write_env_files(config: dict, directory: Path | None = None) -> tuple[Path, Path, Path]:
    directory = directory or default_state_dir()
    directory.mkdir(parents=True, exist_ok=True)
    env_json = directory / "environment.json"
    env_sh = directory / "environment.sh"
    env_ps1 = directory / "activate.ps1"

    env_json.write_text(json.dumps(config, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    prefixes = [value for value in config.get("tool_paths", {}).values() if value]
    shell_lines = ["#!/bin/sh"]
    for key, value in config.get("variables", {}).items():
        shell_lines.append(f"export {key}={json.dumps(value)}")
    if prefixes:
        shell_lines.append(f"export PATH={json.dumps(os.pathsep.join(prefixes))}:$PATH")
    shell_lines.append("")
    env_sh.write_text("\n".join(shell_lines), encoding="utf-8")

    ps_lines = ["# Generated by eSim Tool Manager", ""]
    for key, value in config.get("variables", {}).items():
        ps_lines.append(f'$env:{key} = "{value.replace(chr(34), chr(92) + chr(34))}"')
    if prefixes:
        joined = ";".join(prefixes)
        ps_lines.append(f'$env:PATH = "{joined};$env:PATH"')
    ps_lines.append("")
    env_ps1.write_text("\n".join(ps_lines), encoding="utf-8")

    return env_json, env_sh, env_ps1


def apply_user_environment(config: dict) -> Path:
    state = default_state_dir()
    state.mkdir(parents=True, exist_ok=True)

    if detect_platform() == "windows":
        target = state / "activate.ps1"
        _, _, generated = write_env_files(config, state)
        return generated

    profile = Path.home() / ".profile"
    start = "# >>> eSim Tool Manager >>>"
    end = "# <<< eSim Tool Manager <<<"
    existing = profile.read_text(encoding="utf-8") if profile.exists() else ""

    block = [start]
    for key, value in config.get("variables", {}).items():
        block.append(f"export {key}={json.dumps(value)}")
    prefixes = [value for value in config.get("tool_paths", {}).values() if value]
    if prefixes:
        block.append(f"export PATH={json.dumps(os.pathsep.join(prefixes))}:$PATH")
    block.append(end)
    new_block = "\n".join(block)
    pattern = re.compile(re.escape(start) + r".*?" + re.escape(end), re.S)
    updated = pattern.sub(new_block, existing) if pattern.search(existing) else (existing.rstrip() + "\n\n" + new_block + "\n")
    profile.write_text(updated, encoding="utf-8")
    return profile


def apply_and_log(config: dict) -> Path:
    target = apply_user_environment(config)
    log_event("configure_apply", {"target": str(target)})
    return target
